title: |`md
  # Software System - System Context
`| {
  near: top-center
}
direction: down
style: {
  fill-pattern: lines
}
container_1: {
  label: "User\n[Person]"
  shape: rectangle
  tooltip: "A user of my software system."
  style: {
    fill: "#dddddd"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#9a9a9a"
  }
}
container_2: {
  label: "Software System\n[Software System]"
  shape: rectangle
  tooltip: "My software system."
  style: {
    fill: "#dddddd"
    fill-pattern: dots
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#9a9a9a"
  }
}

container_1 -> container_2: {
  label: "Uses"
  style: {
    font-size: 24
    opacity: 1.0
    stroke: "#707070"
    stroke-dash: 5
    stroke-width: 2
  }
}
