title: |`md
  # System Landscape
`| {
  near: top-center
}
direction: down
"group_Department A": {
  label: "Department A"
  style: {
    fill: "white"
    stroke: "black"
  }
}
"group_Department A"."group_Team 1": {
  label: "Team 1"
  style: {
    fill: "white"
    stroke: "black"
  }
}
"group_Department A"."group_Team 1".container_8: {
  label: "D\n[Software System]"
  shape: rectangle
  style: {
    fill: "#dddddd"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#9a9a9a"
  }
}
"group_Organisation": {
  label: "Organisation"
  style: {
    fill: "white"
    stroke: "black"
  }
}
"group_Organisation"."group_Department A": {
  label: "Department A"
  style: {
    fill: "white"
    stroke: "black"
  }
}
"group_Organisation"."group_Department B": {
  label: "Department B"
  style: {
    fill: "white"
    stroke: "black"
  }
}
"group_Organisation"."group_Department A".container_1: {
  label: "A\n[Software System]"
  shape: rectangle
  style: {
    fill: "#dddddd"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#9a9a9a"
  }
}
"group_Organisation"."group_Department B".container_6: {
  label: "B\n[Software System]"
  shape: rectangle
  style: {
    fill: "#dddddd"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#9a9a9a"
  }
}
"group_Organisation".container_7: {
  label: "C\n[Software System]"
  shape: rectangle
  style: {
    fill: "#dddddd"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#9a9a9a"
  }
}

