title: |`md
  # Internet Banking System - API Application - Components
`| {
  near: top-center
}
steps: {
  1: {
    container_17: {
      label: "Single-Page Application\n[Container: JavaScript and Angular]"
      shape: rectangle
      tooltip: "Provides all of the Internet banking functionality to customers via their web browser."
      style: {
        fill: "#438dd5"
        font-color: "#ffffff"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#2e6295"
      }
    }
    container_18: {
      label: "Mobile App\n[Container: Xamarin]"
      shape: rectangle
      tooltip: "Provides a limited subset of the Internet banking functionality to customers via their mobile device."
      style: {
        fill: "#438dd5"
        font-color: "#ffffff"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#2e6295"
      }
    }
    container_21: {
      label: "Database\n[Container: Oracle Database Schema]"
      shape: cylinder
      tooltip: "Stores user registration information, hashed authentication credentials, access logs, etc."
      style: {
        fill: "#438dd5"
        font-color: "#ffffff"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#2e6295"
      }
    }
    container_4: {
      label: "Mainframe Banking System\n[Software System]"
      shape: rectangle
      tooltip: "Stores all of the core banking information about customers, accounts, transactions, etc."
      style: {
        fill: "#999999"
        font-color: "#ffffff"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#6b6b6b"
      }
    }
    container_6: {
      label: "E-mail System\n[Software System]"
      shape: rectangle
      tooltip: "The internal Microsoft Exchange e-mail system."
      style: {
        fill: "#999999"
        font-color: "#ffffff"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#6b6b6b"
      }
    }

  }
  2: {
    container_20: {
      label: "API Application\n[Container: Java and Spring MVC]"
      shape: rectangle
      tooltip: "Provides Internet banking functionality via a JSON/HTTPS API."
      style: {
        fill: "#438dd5"
        font-color: "#ffffff"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#2e6295"
      }
    }
    container_20.container_29: {
      label: "Sign In Controller\n[Component: Spring MVC Rest Controller]"
      shape: rectangle
      tooltip: "Allows users to sign in to the Internet Banking System."
      style: {
        fill: "#85bbf0"
        font-color: "#000000"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#5d82a8"
      }
    }
    container_20.container_32: {
      label: "Security Component\n[Component: Spring Bean]"
      shape: rectangle
      tooltip: "Provides functionality related to signing in, changing passwords, etc."
      style: {
        fill: "#85bbf0"
        font-color: "#000000"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#5d82a8"
      }
    }

    container_17 -> container_20.container_29: {
      label: "Makes API calls to\n[JSON/HTTPS]"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
    container_18 -> container_20.container_29: {
      label: "Makes API calls to\n[JSON/HTTPS]"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
    container_20.container_29 -> container_20.container_32: {
      label: "Uses"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
    container_20.container_32 -> container_21: {
      label: "Reads from and writes to\n[JDBC]"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
  }
  3: {
    container_20.container_30: {
      label: "Accounts Summary Controller\n[Component: Spring MVC Rest Controller]"
      shape: rectangle
      tooltip: "Provides customers with a summary of their bank accounts."
      style: {
        fill: "#85bbf0"
        font-color: "#000000"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#5d82a8"
      }
    }
    container_20.container_33: {
      label: "Mainframe Banking System Facade\n[Component: Spring Bean]"
      shape: rectangle
      tooltip: "A facade onto the mainframe banking system."
      style: {
        fill: "#85bbf0"
        font-color: "#000000"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#5d82a8"
      }
    }

    container_17 -> container_20.container_30: {
      label: "Makes API calls to\n[JSON/HTTPS]"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
    container_18 -> container_20.container_30: {
      label: "Makes API calls to\n[JSON/HTTPS]"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
    container_20.container_30 -> container_20.container_33: {
      label: "Uses"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
    container_20.container_33 -> container_4: {
      label: "Uses\n[XML/HTTPS]"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
  }
  4: {
    container_20.container_31: {
      label: "Reset Password Controller\n[Component: Spring MVC Rest Controller]"
      shape: rectangle
      tooltip: "Allows users to reset their passwords with a single use URL."
      style: {
        fill: "#85bbf0"
        font-color: "#000000"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#5d82a8"
      }
    }
    container_20.container_34: {
      label: "E-mail Component\n[Component: Spring Bean]"
      shape: rectangle
      tooltip: "Sends e-mails to users."
      style: {
        fill: "#85bbf0"
        font-color: "#000000"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#5d82a8"
      }
    }

    container_17 -> container_20.container_31: {
      label: "Makes API calls to\n[JSON/HTTPS]"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
    container_18 -> container_20.container_31: {
      label: "Makes API calls to\n[JSON/HTTPS]"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
    container_20.container_31 -> container_20.container_32: {
      label: "Uses"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
    container_20.container_31 -> container_20.container_34: {
      label: "Uses"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
    container_20.container_34 -> container_6: {
      label: "Sends e-mail using"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
  }
}
