title: |`md
  # Internet Banking System - System Context
`| {
  near: top-center
}
direction: down
steps: {
  1: {
    "group_Big Bank plc".container_7: {
      label: "Internet Banking System\n[Software System]"
      shape: rectangle
      tooltip: "Allows customers to view information about their bank accounts, and make payments."
      style: {
        fill: "#1168bd"
        font-color: "#ffffff"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#0b4884"
      }
    }
    "group_Big Bank plc": {
      label: "Big Bank plc"
      shape: rectangle
      style: {
        fill: "#ffffff"
        font-color: "#cccccc"
        font-size: 24
        opacity: 1.0
        stroke: "#cccccc"
        stroke-dash: 5
        stroke-width: 2
      }
    }

  }
  2: {
    container_1: {
      label: "Personal Banking Customer\n[Person]"
      shape: person
      tooltip: "A customer of the bank, with personal bank accounts."
      style: {
        fill: "#08427b"
        font-color: "#ffffff"
        font-size: 22
        multiple: false
        opacity: 1.0
        stroke: "#052e56"
      }
    }

    container_1 -> "group_Big Bank plc".container_7: {
      label: "Views account balances, and makes payments using"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
  }
  3: {
    "group_Big Bank plc".container_4: {
      label: "Mainframe Banking System\n[Software System]"
      shape: rectangle
      tooltip: "Stores all of the core banking information about customers, accounts, transactions, etc."
      style: {
        fill: "#999999"
        font-color: "#ffffff"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#6b6b6b"
      }
    }

    "group_Big Bank plc".container_7 -> "group_Big Bank plc".container_4: {
      label: "Gets account information from, and makes payments using"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
  }
  4: {
    "group_Big Bank plc".container_5: {
      label: "E-mail System\n[Software System]"
      shape: rectangle
      tooltip: "The internal Microsoft Exchange e-mail system."
      style: {
        fill: "#999999"
        font-color: "#ffffff"
        font-size: 24
        multiple: false
        opacity: 1.0
        stroke: "#6b6b6b"
      }
    }

    "group_Big Bank plc".container_7 -> "group_Big Bank plc".container_5: {
      label: "Sends e-mail using"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
    "group_Big Bank plc".container_5 -> container_1: {
      label: "Sends e-mails to"
      style: {
        font-size: 24
        opacity: 1.0
        stroke: "#707070"
        stroke-dash: 5
        stroke-width: 2
      }
    }
  }
}
