title: |`md
  # Spring PetClinic - Deployment - Live
`| {
  near: top-center
}
container_5: {
  icon: "https://static.structurizr.com/themes/amazon-web-services-2020.04.30/aws-cloud.png"
  label: "Amazon Web Services\n[Deployment Node]"
  shape: rectangle
  style: {
    fill: "#ffffff"
    font-color: "#232f3e"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#232f3e"
  }
}
container_5.container_6: {
  icon: "https://static.structurizr.com/themes/amazon-web-services-2020.04.30/region.png"
  label: "US-East-1\n[Deployment Node]"
  shape: rectangle
  style: {
    fill: "#ffffff"
    font-color: "#147eba"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#147eba"
  }
}
container_5.container_6.container_12: {
  icon: "https://static.structurizr.com/themes/amazon-web-services-2020.04.30/amazon-rds.png"
  label: "Amazon RDS\n[Deployment Node]"
  shape: rectangle
  style: {
    fill: "#ffffff"
    font-color: "#3b48cc"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#3b48cc"
  }
}
container_5.container_6.container_12.container_13: {
  icon: "https://static.structurizr.com/themes/amazon-web-services-2020.04.30/amazon-rds-mysql-instance.png"
  label: "MySQL\n[Deployment Node]"
  shape: rectangle
  style: {
    fill: "#ffffff"
    font-color: "#3b48cc"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#3b48cc"
  }
}
container_5.container_6.container_12.container_13.container_14: {
  label: "Database"
  shape: cylinder
  style: {
    fill: "#ffffff"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#b2b2b2"
  }
}
container_5.container_6.container_7: {
  icon: "https://static.structurizr.com/themes/amazon-web-services-2020.04.30/amazon-route-53.png"
  label: "Route 53\n[Infrastructure Node]"
  shape: rectangle
  tooltip: "Highly available and scalable cloud DNS service."
  style: {
    fill: "#ffffff"
    font-color: "#693cc5"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#693cc5"
  }
}
container_5.container_6.container_8: {
  icon: "https://static.structurizr.com/themes/amazon-web-services-2020.04.30/elastic-load-balancing.png"
  label: "Elastic Load Balancer\n[Infrastructure Node]"
  shape: rectangle
  tooltip: "Automatically distributes incoming application traffic."
  style: {
    fill: "#ffffff"
    font-color: "#693cc5"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#693cc5"
  }
}
container_5.container_6.container_9: {
  icon: "https://static.structurizr.com/themes/amazon-web-services-2020.04.30/aws-auto-scaling.png"
  label: "Autoscaling group\n[Deployment Node]"
  shape: rectangle
  style: {
    fill: "#ffffff"
    font-color: "#cc2264"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#cc2264"
  }
}
container_5.container_6.container_9.container_10: {
  icon: "https://static.structurizr.com/themes/amazon-web-services-2020.04.30/amazon-ec2.png"
  label: "Amazon EC2\n[Deployment Node]"
  shape: rectangle
  style: {
    fill: "#ffffff"
    font-color: "#d86613"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#d86613"
  }
}
container_5.container_6.container_9.container_10.container_11: {
  label: "Web Application"
  shape: rectangle
  style: {
    fill: "#ffffff"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#b2b2b2"
  }
}
container_5.container_6.container_9.container_10.container_11 -> container_5.container_6.container_12.container_13.container_14: {
  label: "Reads from and writes to\n[MySQL Protocol/SSL]"
  style: {
    font-size: 24
    opacity: 1.0
    stroke: "#707070"
    stroke-dash: 5
    stroke-width: 2
  }
}
container_5.container_6.container_7 -> container_5.container_6.container_8: {
  label: "Forwards requests to\n[HTTPS]"
  style: {
    font-size: 24
    opacity: 1.0
    stroke: "#707070"
    stroke-dash: 5
    stroke-width: 2
  }
}
container_5.container_6.container_8 -> container_5.container_6.container_9.container_10.container_11: {
  label: "Forwards requests to\n[HTTPS]"
  style: {
    font-size: 24
    opacity: 1.0
    stroke: "#707070"
    stroke-dash: 5
    stroke-width: 2
  }
}
