title: |`md
  # System Landscape for Big Bank plc
`| {
  near: top-center
  style: {
  }
}
"enterprise_Big Bank plc": {
  label: "Big Bank plc"
  style: {
    fill: "white"
    stroke: "black"
  }
  container_12: {
    label: "Customer Service Staff\n[Person]"
    shape: person
    tooltip: "Customer service staff within the bank."
    style: {
      fill: "#999999"
      font-color: "#ffffff"
      font-size: 22
      multiple: false
      opacity: 1.0
      stroke: "#6b6b6b"
    }
  }
  container_15: {
    label: "Back Office Staff\n[Person]"
    shape: person
    tooltip: "Administration and support staff within the bank."
    style: {
      fill: "#999999"
      font-color: "#ffffff"
      font-size: 22
      multiple: false
      opacity: 1.0
      stroke: "#6b6b6b"
    }
  }
  container_2: {
    label: "Internet Banking System\n[Software System]"
    shape: rectangle
    tooltip: "Allows customers to view information about their bank accounts, and make payments."
    style: {
      fill: "#1168bd"
      font-color: "#ffffff"
      font-size: 24
      multiple: false
      opacity: 1.0
      stroke: "#0b4884"
    }
  }
  container_4: {
    label: "Mainframe Banking System\n[Software System]"
    shape: rectangle
    tooltip: "Stores all of the core banking information about customers, accounts, transactions, etc."
    style: {
      fill: "#999999"
      font-color: "#ffffff"
      font-size: 24
      multiple: false
      opacity: 1.0
      stroke: "#6b6b6b"
    }
  }
  container_6: {
    label: "E-mail System\n[Software System]"
    shape: rectangle
    tooltip: "The internal Microsoft Exchange e-mail system."
    style: {
      fill: "#999999"
      font-color: "#ffffff"
      font-size: 24
      multiple: false
      opacity: 1.0
      stroke: "#6b6b6b"
    }
  }
  container_9: {
    label: "ATM\n[Software System]"
    shape: rectangle
    tooltip: "Allows customers to withdraw cash."
    style: {
      fill: "#999999"
      font-color: "#ffffff"
      font-size: 24
      multiple: false
      opacity: 1.0
      stroke: "#6b6b6b"
    }
  }
}
container_1: {
  label: "Personal Banking Customer\n[Person]"
  shape: person
  tooltip: "A customer of the bank, with personal bank accounts."
  style: {
    fill: "#08427b"
    font-color: "#ffffff"
    font-size: 22
    multiple: false
    opacity: 1.0
    stroke: "#052e56"
  }
}

"enterprise_Big Bank plc".container_9 -> "enterprise_Big Bank plc".container_4: {
  label: "Uses"
  style: {
    opacity: 1.0
    stroke: "#707070"
    stroke-width: 2
  }
}
container_1 -> "enterprise_Big Bank plc".container_9: {
  label: "Withdraws cash using"
  style: {
    opacity: 1.0
    stroke: "#707070"
    stroke-width: 2
  }
}
"enterprise_Big Bank plc".container_12 -> "enterprise_Big Bank plc".container_4: {
  label: "Uses"
  style: {
    opacity: 1.0
    stroke: "#707070"
    stroke-width: 2
  }
}
container_1 -> "enterprise_Big Bank plc".container_12: {
  label: "Asks questions to\n[Telephone]"
  style: {
    opacity: 1.0
    stroke: "#707070"
    stroke-width: 2
  }
}
"enterprise_Big Bank plc".container_15 -> "enterprise_Big Bank plc".container_4: {
  label: "Uses"
  style: {
    opacity: 1.0
    stroke: "#707070"
    stroke-width: 2
  }
}
container_1 -> "enterprise_Big Bank plc".container_2: {
  label: "Views account balances, and makes payments using"
  style: {
    opacity: 1.0
    stroke: "#707070"
    stroke-width: 2
  }
}
"enterprise_Big Bank plc".container_2 -> "enterprise_Big Bank plc".container_4: {
  label: "Gets account information from, and makes payments using"
  style: {
    opacity: 1.0
    stroke: "#707070"
    stroke-width: 2
  }
}
"enterprise_Big Bank plc".container_2 -> "enterprise_Big Bank plc".container_6: {
  label: "Sends e-mail using"
  style: {
    opacity: 1.0
    stroke: "#707070"
    stroke-width: 2
  }
}
"enterprise_Big Bank plc".container_6 -> container_1: {
  label: "Sends e-mails to"
  style: {
    opacity: 1.0
    stroke: "#707070"
    stroke-width: 2
  }
}
