title: |`md
  # D - F - Components
`| {
  near: top-center
}
direction: down
container_3: {
  label: "C\n[Software System]"
  shape: rectangle
  style: {
    fill: "#dddddd"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#9a9a9a"
  }
}

container_6: {
  label: "F\n[Container]"
  shape: rectangle
  style: {
    fill: "#dddddd"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#9a9a9a"
  }
}
container_6."group_Group 4": {
  label: "Group 4"
  shape: rectangle
  style: {
    fill: "#ffffff"
    font-color: "#cccccc"
    font-size: 24
    opacity: 1.0
    stroke: "#cccccc"
    stroke-dash: 5
    stroke-width: 2
  }
}
container_6.container_7: {
  label: "G\n[Component]"
  shape: rectangle
  style: {
    fill: "#dddddd"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#9a9a9a"
  }
}
container_6."group_Group 4".container_8: {
  label: "H\n[Component]"
  shape: rectangle
  style: {
    fill: "#dddddd"
    font-color: "#000000"
    font-size: 24
    multiple: false
    opacity: 1.0
    stroke: "#9a9a9a"
  }
}
container_3 -> container_6.container_7: {
  label: ""
  style: {
    font-size: 24
    opacity: 1.0
    stroke: "#707070"
    stroke-dash: 5
    stroke-width: 2
  }
}
container_3 -> container_6."group_Group 4".container_8: {
  label: ""
  style: {
    font-size: 24
    opacity: 1.0
    stroke: "#707070"
    stroke-dash: 5
    stroke-width: 2
  }
}
